### ISSUE TITLE
No license provided

### ISSUE THREAD

**Issue by RobWC** [DealerDotCom/terraform-provider-bigip#1]
I would be interested in using/contributing to this for a project. However I would need you to specify a license to make sure it complies with my org's OSS policy.

**Comment by aburnett** [comment]
I've been meaning to get to that. We have an open source policy here as well. Let me track down the details of that to make sure I put the correct license on.

**Comment by RobWC** [comment]
Thank you!

**Comment by aburnett** [comment]
Added MPL.

**Comment by RobWC** [comment]
:+1:  :facepunch:
