### ISSUE TITLE
Ability to add a named SNAT pool to a virtual server

### ISSUE THREAD

**Issue by RobWC** [DealerDotCom/terraform-provider-bigip#16]
Currently when using SNAT it requires you to specify a pool name in addition to specifying "snat" for source_address_translation.

Error Message

```
* bigip_ltm_virtual_server.test_vs: 01071811:3: Virtual Server /Common/TEST-SERVER references non-existent snatpool <no name>.
```

**Comment by RobWC** [comment]
I will not have time to add this via pull request.

😭

**Comment by aburnett** [comment]
Unfortunately I no longer have access to an F5. So I leave this to you, the devoted community 😉 .

**Comment by pdxfixit** [comment]
PR #34 merged.  Closing.
