### ISSUE TITLE
Specify context for Profiles on Virtual Servers

### ISSUE THREAD

**Issue by RobWC** [DealerDotCom/terraform-provider-bigip#17]
When creating a virtual server you are unable to specify the context (client or server) to a profile. It currently applies the default "all" to the context. This applies to client and server. This also seems to be an issue in the upstream driver as it only allows you to specify a profile name and not a context. In the REST API it specifies that "context" is an additional key/value that can be provided.

Error Message

```
* bigip_ltm_virtual_server.test_vs: 01070097:3: Virtual server /Common/TEST-SERVER lists duplicate profiles.
```

**Comment by aburnett** [comment]
Added support in go-bigip.

https://github.com/scottdware/go-bigip/commit/4ac131a02acccad76693c2dbfdcda768989131c7
