### ISSUE TITLE
Built release images are built with Terraform 0.7 libs

### ISSUE THREAD

**Issue by RobWC** [DealerDotCom/terraform-provider-bigip#18]
When attempting to use the newly released plugin I see this error:

```
Incompatible API version with plugin. Plugin version: 1, Ours: 2
```

After doing some research I found the following: [Compile with tag v0.6.16](https://groups.google.com/forum/#!msg/terraform-tool/a1agp4CAEDk/En27utjUBQAJ)

**Comment by aburnett** [comment]
Yikes, ok. I can take that...

**Comment by RobWC** [comment]
Its pretty annoying stuff! Thanks for your help!

**Comment by aburnett** [comment]
Try https://github.com/DealerDotCom/terraform-provider-bigip/releases/tag/v0.4.1

**Comment by RobWC** [comment]
Looks spiffy! Thank you very much F5 warrior!
