### ISSUE TITLE
Public facing F5

### ISSUE THREAD

**Issue by aburnett** [DealerDotCom/terraform-provider-bigip#20]
To help further the development of this plugin and possibly make it viable for contribution as a built in provider it would be helpful to have a publicly facing F5 (Virtual Edition, Lab or "Good" licence) that we could use to run the acceptance test suite against.

If this is something you or your company would be willing to sponsor please let us know! Thanks!

**Comment by RobWC** [comment]
Let me see what I can do.

**Comment by RobWC** [comment]
OK it looks like I have a license we can use. Do you want this setup as a shared VM in something like AWS?

**Comment by aburnett** [comment]
Awesome. AWS would be the best option. We should think about how best to set this up. Don't want to burn $$ just having it running all the time and also need a good way to reset it to a known good state. 

Maybe something like a post commit hook that kicks off a CodePipeline to spin up the F5 instance, run the acceptance tests, publish the results somewhere then shut it all down.

**Comment by aburnett** [comment]
I just successfully ran the tests against a free trial of F5 VE in AWS. It can run in EC2 Classic so we don't need a VPC or anything.

Maybe just an AWS access key w/ permissions to spin up an EC2 instance is all we need. Create an F5 virtual edition instance, go through the setup wizard and create a new AMI off it once it's complete. Then in Travis we can install the aws cli and spin the instance up/down during the build.

**Comment by aburnett** [comment]
I created a terraform file for spinning up a possible infrastructure. Can you use chef to provision the F5 to get past the setup wizard? If so maybe we could add an OpsWorks config.

https://github.com/DealerDotCom/terraform-provider-bigip/blob/test-infrastructure/infrastructure/test-env-setup.tf

**Comment by RobWC** [comment]
Have the stuff I just don't have the cycles at the moment. But this is still on my radar.

**Comment by pdxfixit** [comment]
https://github.com/f5devcentral/terraform-provider-bigip now exists, and (presumably) has official support from F5. Closing.
