### ISSUE TITLE
Failing to create monitor

### ISSUE THREAD

**Issue by pryorda** [DealerDotCom/terraform-provider-bigip#23]
For some reason when I try to create a monitor its falling into

```
func resourceBigipLtmMonitorRead(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*bigip.BigIP)

    name := d.Id()

    monitors, err := client.Monitors()
    if err != nil {
        return err
    }
    for _, m := range monitors {
        if m.FullPath == name {
            d.Set("interval", m.Interval)
            d.Set("timeout", m.Timeout)
            d.Set("send", m.SendString)
            d.Set("receive", m.ReceiveString)
            d.Set("receive_disable", m.ReceiveDisable)
            d.Set("reverse", m.Reverse)
            d.Set("transparent", m.Transparent)
            d.Set("ip_dscp", m.IPDSCP)
            d.Set("time_until_up", m.TimeUntilUp)
            d.Set("manual_resume", m.ManualResume)
            d.Set("parent", m.ParentMonitor)
            d.Set("name", name)
            return nil
        }
    }
    return fmt.Errorf("Couldn't find monitor ", name)
}
```

Terraform version: Terraform v0.6.16
Terraform bigip version: Latest from releases
File: main.tf

```
provider "bigip" {
  address = "url"
  username = "usr"
  password = "password"
}

resource "bigip_ltm_monitor" "monitor" {
  name = "/Common/${var.monitor_name}"
  parent = "/Common/${var.parent_monitor}"
  send = "${var.monitor_send}"
  timeout = "${var.monitor_timeout}"
  interval = "${var.monitor_interval}"
  receive = "${var.monitor_receive}"
}
```

Output: 

```
dpryor@co007-linux:~/git/terraform-bigip$ terraform apply
bigip_ltm_monitor.monitor: Refreshing state... (ID: /Common/my_monitor)
bigip_ltm_monitor.monitor: Creating...
  interval:      "" => "5"
  ip_dscp:       "" => "0"
  manual_resume: "" => "false"
  name:          "" => "/Common/my_monitor"
  parent:        "" => "/Common/http"
  receive:       "" => "test"
  reverse:       "" => "false"
  send:          "" => "GET / \\r\\n"
  time_until_up: "" => "0"
  timeout:       "" => "15"
  transparent:   "" => "false"
Error applying plan:

1 error(s) occurred:

* bigip_ltm_monitor.monitor: Couldn't find monitor %!(EXTRA string=/Common/my_monitor)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
dpryor@co007-linux:~/git/terraform-bigip$ ls
```

**Comment by aburnett** [comment]
Is there an existing monitor on your F5 called my_monitor?

**Comment by pryorda** [comment]
@aburnett  This might be my fault. I was trying against a f5 11.x lb. Im working with f5 to see if icontrol even works on 11.x now. I tested on 12.x and it works fine. Ill close as soon as I verify.

**Comment by aburnett** [comment]
Hmm, we test against 11.5. What specific version of 11 were you pointing at?

**Comment by pryorda** [comment]
11.4 :(

**Comment by aburnett** [comment]
If you have time to dig in it would be appreciated!

If it's falling into `resourceBigipLtmMonitorRead` that means `resourceBigipLtmMonitorExists` is returning true. Off the top of my head does the REST API in 11.4 not return fullPath or not return the partition + name in the fullPath?

```
curl -u 'username:password' 'https://your-ltm/mgmt/tm/ltm/monitor/http'
```

**Comment by aburnett** [comment]
Oh, also, did you have tfstate file generated by a pre v0.4 version of this plugin?

**Comment by pryorda** [comment]
I did not. I started with this provider the night I submitted this. to your other question here is the result, which I'm assuming is not what we want.  

```
dpryor@co007-linux:~$ curl -sku 'details' 'https://172.16.x.x/mgmt/tm/ltm/monitor/http' |python -mjson.tool
{
    "code": 404,
    "errorStack": [
        "com.f5.rest.common.RestWorkerUriNotFoundException: http://localhost:8100/mgmt/tm/ltm/monitor/http",
        "at com.f5.rest.common.RestServer.trySendInProcess(RestServer.java:126)",
        "at com.f5.rest.common.RestRequestReceiver.dispatchToService(RestRequestReceiver.java:93)",
        "at com.f5.rest.common.RestRequestReceiver.processNext(RestRequestReceiver.java:57)",
        "at com.f5.rest.common.RestHelper$2.run(RestHelper.java:1480)",
        "at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)",
        "at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)",
        "at java.lang.Thread.run(Unknown Source)\n"
    ],
    "message": "http://localhost:8100/mgmt/tm/ltm/monitor/http",
    "restOperationId": 22660217
}
dpryor@co007-linux:~$ 
```

**Comment by aburnett** [comment]
Odd, what about at just `/mgmt/tm/ltm` and `/mgmt/tm/ltm/monitor`?

FWIW, I found the following quote on the [dev central](https://devcentral.f5.com/questions/big-ip-icontrol-rest-api)

> iControl REST in 11.4 was Early Access, and did not have all features worked into the product. It was not ready for production. iControl Rest in 11.5.1 was General Release and was fully supported.

**Comment by pryorda** [comment]
I fixed that last issue by running the following on the lb:

```
touch /etc/bigstart/scripts/scim
bigstart add --default icrd
bigstart enable icrd
bigstart start icrd
ln -s /etc/bigstart/scripts/icrd /service/icrd/run
```

Result from the curl command is all the items that rely on the monitor. Example. 

```
      {
            "defaultsFrom": "http",
            "description": "\"test for get request of / on xxx\"",
            "destination": "*:*",
            "generation": 0,
            "interval": 5,
            "kind": "tm:ltm:monitor:http:httpstate",
            "lastUpdatedMicros": 0,
            "manualResume": "disabled",
            "name": "qa-www_cms_test",
            "recv": "\"200 OK\"",
            "reverse": "disabled",
            "selfLink": "https://localhost/mgmt/tm/ltm/monitor/http/qa-www",
            "send": "\"GET / HTTP/1.1\\\\r\\\\nHost: qa-www.xx\\\\r\\\\nConnection: Close\\\\r\\\\n\\\\r\\\\n\"",
            "timeUntilUp": 0,
            "timeout": 5,
            "transparent": "disabled",
            "upInterval": 0
        },
```

Edit: Sorry bad paste. Looks like you're right. Its is missing full path.

**Comment by aburnett** [comment]
Well crap. It's missing `partition` as well, so that's extra unhelpful. I'm inclined to say we won't support 11.4 for now. Thanks for finding this though! I'll update the docs.

In the short term you could try downgrading to [v0.3.1](https://github.com/DealerDotCom/terraform-provider-bigip/releases/tag/v0.3.1). That uses `name` instead of `fullPath`. Though, there are a lot of inconsistencies in the API where the name field actually contained a fullPath (hence the switch in v0.4). Though, maybe that's not the case in 11.4. Let us know & close if that gets you unstuck for now. If you want to suggest 11.4 support as an enhancement please open a separate issue (or pull request! =).

**Comment by pryorda** [comment]
We are upgrading this env to 11.6.1 so you can close this.

Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Adam Burnett notifications@github.com Date: 6/13/16  6:12 PM  (GMT-07:00) To: DealerDotCom/terraform-provider-bigip terraform-provider-bigip@noreply.github.com Cc: Daniel Pryor daniel@pryorda.net, Author author@noreply.github.com Subject: Re: [DealerDotCom/terraform-provider-bigip] Failing to create monitor (#23) 
Well crap. It's missing partition as well, so that's extra unhelpful. I'm inclined to say we won't support 11.4 for now. Thanks for finding this though! I'll update the docs.

In the short term you could try downgrading to v0.3.1. That uses name instead of fullPath. Though, there are a lot of inconsistencies in the API where the name field actually contained a fullPath (hence the switch in v0.4). Though, maybe that's not the case in 11.4. Let us know & close if that gets you unstuck for now. If you want to suggest 11.4 support as an enhancement please open a separate issue (or pull request! =).

**Comment by aburnett** [comment]
Ok, if you get a chance it would be good to get the plugin tested against 11.6. If you could run [the acceptance tests](https://github.com/DealerDotCom/terraform-provider-bigip#testing) and report back that would be helpful. Thanks!

**Comment by pryorda** [comment]
I should be getting the LB updated today or tomorrow. Are there any prereqs for the acceptance test? Go, godeps, else?

**Comment by aburnett** [comment]
Should just be able to run that command from the readme.

**Comment by pryorda** [comment]
@aburnett 

11.6

```
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestBigipLtmIRule_create
--- PASS: TestBigipLtmIRule_create (3.09s)
=== RUN   TestBigipLtmMonitor_create
--- PASS: TestBigipLtmMonitor_create (6.03s)
=== RUN   TestBigipLtmNode_create
--- PASS: TestBigipLtmNode_create (3.96s)
=== RUN   TestMapEntity
--- PASS: TestMapEntity (0.00s)
=== RUN   TestMapFromEntity
--- PASS: TestMapFromEntity (0.00s)
=== RUN   TestBigipLtmPool_create
--- PASS: TestBigipLtmPool_create (4.78s)
=== RUN   TestBigipLtmVA_create
--- PASS: TestBigipLtmVA_create (5.41s)
=== RUN   TestBigipLtmVS_create
--- PASS: TestBigipLtmVS_create (8.28s)
=== RUN   TestValidStringValue
--- PASS: TestValidStringValue (0.00s)
=== RUN   TestInvalidStringValue
--- PASS: TestInvalidStringValue (0.00s)
=== RUN   TestF5NameString
--- PASS: TestF5NameString (0.00s)
=== RUN   TestF5NameSet
--- PASS: TestF5NameSet (0.00s)
=== RUN   TestF5NameList
--- PASS: TestF5NameList (0.00s)
PASS
ok      github.com/DealerDotCom/terraform-provider-bigip/bigip  31.552s
```

12.0

```
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestBigipLtmIRule_create
--- PASS: TestBigipLtmIRule_create (5.28s)
=== RUN   TestBigipLtmMonitor_create
--- PASS: TestBigipLtmMonitor_create (7.76s)
=== RUN   TestBigipLtmNode_create
--- PASS: TestBigipLtmNode_create (5.06s)
=== RUN   TestMapEntity
--- PASS: TestMapEntity (0.00s)
=== RUN   TestMapFromEntity
--- PASS: TestMapFromEntity (0.00s)
=== RUN   TestBigipLtmPool_create
--- PASS: TestBigipLtmPool_create (5.38s)
=== RUN   TestBigipLtmVA_create
--- PASS: TestBigipLtmVA_create (5.63s)
=== RUN   TestBigipLtmVS_create
--- PASS: TestBigipLtmVS_create (6.67s)
=== RUN   TestValidStringValue
--- PASS: TestValidStringValue (0.00s)
=== RUN   TestInvalidStringValue
--- PASS: TestInvalidStringValue (0.00s)
=== RUN   TestF5NameString
--- PASS: TestF5NameString (0.00s)
=== RUN   TestF5NameSet
--- PASS: TestF5NameSet (0.00s)
=== RUN   TestF5NameList
--- PASS: TestF5NameList (0.00s)
PASS
ok      github.com/DealerDotCom/terraform-provider-bigip/bigip  35.783s
```

**Comment by aburnett** [comment]
Awesome! Thanks for verifying!
