### ISSUE TITLE
New virtual server with no profiles causes crash

### ISSUE THREAD

**Issue by aburnett** [DealerDotCom/terraform-provider-bigip#29]
Creating a new virtual server crashes if no profiles are specified. 

I believe these parameters are optional (i.e. the BigIP will assign defaults) so there should be a null checks around the profiles similar to how it is done in `resourceBigipLtmVirtualServerUpdate` with `GetOk`.

**Comment by pdxfixit** [comment]
Posting my own theory ( also in #28 ), just to think-out-loud -- this looks really interesting;

```
  profiles.#:                 "0" => "2"
  profiles.1139270267:        "" => "/Common/tcp"
  profiles.576276785:         "" => "/Common/http"
  server_profiles.#:          "" => "<computed>"
```

I wonder if server_profiles was made to be "0" => "0", if it would pass.

**Comment by pdxfixit** [comment]
Just added PR #31 for this.

Unfortunately, it doesn't follow the suggested pattern. I wasn't able to make that pattern work, b/c as I saw it, GetOk wouldn't work b/c the values weren't yet in memory.

I opted for this method, where we evaluate that profiles is not nil, and that profiles.Profiles is > 0.

Constructive criticism welcomed. :)

**Comment by pdxfixit** [comment]
This is now resolved.

**Comment by pryorda** [comment]
Per @pdxfixit closing this.
