### ISSUE TITLE
Incompatible API version with plugin. Plugin version: 2, Ours: 1

### ISSUE THREAD

**Issue by sizgiyaev** [DealerDotCom/terraform-provider-bigip#37]
Hi,
My terraform version is 0.7.3
I get the subj message when I try to run the **_terraform plan_**.
Is that related to terrafrom itself or to the bigip provider?

**Comment by pdxfixit** [comment]
It's the result of interaction between the two, how the bigip provider communicates with terraform. I'll look into this, and post back here as soon as I can.

**Comment by sizgiyaev** [comment]
Thanks a lot, looking forward for the solution

**Comment by pdxfixit** [comment]
Could you post your terraform files, please? Would be helpful for debugging.

**Comment by sizgiyaev** [comment]
I have just started to evaluate terraform and at this point i'm using very simple configuration just to check capabilities:

variable "bigip_url" {}
variable "bigip_user" {}
variable "bigip_pass" {}
variable "bigip_partition" {}

provider "bigip" {
	address = "${var.bigip_url}"
	username = "${var.bigip_user}"
	password = "${var.bigip_pass}"
	token_auth = "true"
}
resource "bigip_ltm_node" "node" {
	name = "/${var.bigip_partition}/test_node1"
	address = "10.10.10.10"
}

The release of the provider downloaded from here: https://github.com/DealerDotCom/terraform-provider-bigip/releases/download/v0.6.1/terraform-provider-bigip_linux_amd64.tar.gz

**Comment by sizgiyaev** [comment]
i have also tried to compile the provider and got error:
[xxxxx@XXXXXX terraform-provider-bigip]$ make get-deps
terraform-provider-bigip
\# terraform-provider-bigip
./main.go:10: cannot use "github.com/DealerDotCom/terraform-provider-bigip/bigip".Provider (type func() "github.com/DealerDotCom/terraform-provider-bigip/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider) as type "terraform-provider-bigip/vendor/github.com/hashicorp/terraform/plugin".ProviderFunc in field value
make: *** [get-deps] Error 2

**Comment by pdxfixit** [comment]
interesting.  I've not seen that error before.  I'm looking into this issue, but can't guarantee a solution today. (fyi)

**Comment by pdxfixit** [comment]
Looks like they've bumped the API protocol version. (https://github.com/hashicorp/terraform/commit/b3124e16ca7efb6c543a84af8c7951860b3cfb37) I think we're running into this, b/c we're compiling the bigip provider against the HEAD of hashicorp/terraform.  If we checkout v0.7.13, and build against that, I think we'll be in good shape.  I will try this later this evening.

**Comment by leftathome** [comment]
For what it's worth, @pdxfixit is exactly right - it's got to do with whether you pull down the HEAD version of your Terraform plugin dependency that doesn't match what you've got installed and running on a node.  I believe the API bump started during a recent 0.7.x release.  This will only be necessary until Hashicorp releases a Terraform version that supports the new plugin API version.  (My money's on them calling that 0.8.0, because semantic versioning)

This will affect anyone writing pull requests against a Terraform module as well.  Caveat developer...

**Comment by pdxfixit** [comment]
I've gotten caught up with work stuff. I'll bounce back to this as soon as I can, but will likely hold off until 0.8 is released, so we can just upgrade. Fyi.

**Comment by sizgiyaev** [comment]
Any chance to get it resolved? 
i have tried to use terraform 0.8.0 beta2 - the same issue

**Comment by jakauppila** [comment]
+1, any chance of incorporating the changes with 0.8.0? Looks like it was just released 15 minutes ago :)

**Comment by pryorda** [comment]
This is how I got it to work. 

```
go get github.com/hashicorp/terraform
go get github.com/DealerDotCom/terraform-provider-bigip/
```

**Comment by pdxfixit** [comment]
Is anyone still having issues with this, after upgrading to 0.8?

The reports I've received outside GitHub suggest that after upgrading terraform, everything works fine.

**Comment by sizgiyaev** [comment]
looks like it works now. 
Thanks

**Comment by bpoland** [comment]
Looks like Terraform 0.9 has broken things again:

provider.bigip: Incompatible API version with plugin. Plugin version: 2, Ours: 4

**Comment by sizgiyaev** [comment]
@bpoland, have you tried the suggestion of pryorda?

**Comment by bpoland** [comment]
@sizgiyaev thanks, I will try that.  Would still be nice to get an official release with terraform 0.9 support.

**Comment by bpoland** [comment]
Unfortunately pryorda's go get method didn't work for me.  I still get

* provider.bigip: Incompatible API version with plugin. Plugin version: 2, Ours: 4

**Comment by bpoland** [comment]
Is there anyone looking into this?  Would be really nice to use some of the new stuff in terraform 0.9
Thanks!

**Comment by clammers** [comment]
We're also having some issues with the latest stable version. Would be nice to get a new one, maybe as beta - to support latest terraform 0.9.3 as we need new features in terraform

**Comment by pcfens** [comment]
I was able to fix this with
```bash
go get -d github.com/DealerDotCom/terraform-provider-bigip/  #  I used this instead of git clone
cd $GOPATH/src/github.com/DealerDotCom/terraform-provider-bigip/
rm -rf vendor/github.com/hashicorp/terraform
go get -d github.com/hashicorp/terraform
go build
```

I've pushed a working image to the [docker hub](https://hub.docker.com/r/pcfens/terraform-bigip/) in case it helps. The Dockerfile is on [GitHub](https://github.com/pcfens/docker-terraform-bigip).

**Comment by mattcanty** [comment]
Could somebody please make a release with all the changes that are going on?

**Comment by rgoodenb** [comment]
Still no new release with this issue fixed? The latest release does not work with terraform v0.10.6 provider.bigip: Incompatible API version with plugin. Plugin version: 2, Ours: 4.

**Comment by bpoland** [comment]
try @pcfens method above to build it locally.  I was able to build a local copy that works with newer terraform.  Would definitely still be nice to get a release here but it seems like there aren't a lot of people around to support this provider anymore...

**Comment by mattlqx** [comment]
FYI, this provider is becoming active on f5devcentral's org. https://github.com/f5devcentral/terraform-provider-bigip

**Comment by pryorda** [comment]
Interesting.
