### ISSUE TITLE
Update usages of PoolMembers

### ISSUE THREAD

**Issue by aburnett** [DealerDotCom/terraform-provider-bigip#39]
To stay current with the go-bigip library all usages of PoolMembers should be updated to take advantage of the new [method signature](https://github.com/scottdware/go-bigip/commit/7991c71f16ee28a084c8b7223bb0323d256f81cb#diff-54bcb21bdeb634bdd25b6d411f9d4464R769).

**Comment by jakauppila** [comment]
This can be closed with the PR merged.
