### ISSUE TITLE
Good Provider

### ISSUE THREAD

**Issue by pshort** [DealerDotCom/terraform-provider-bigip#4]
Why don't you guys ask this to pushed to the main terraform branch, would be cool to see Big IP in the list of supported providers :)

**Comment by aburnett** [comment]
Thanks @pshort! I think there is some more fit and finish to go to get a minimum set of functionality in place. We're also lacking in the test department for both this plugin and the supporting bigip api wrapper library. I'll see what is involved in getting this included as a built-in provider though.

**Comment by aburnett** [comment]
Tracked with #7
