### ISSUE TITLE
Failing to build provider

### ISSUE THREAD

**Issue by jakauppila** [DealerDotCom/terraform-provider-bigip#41]
I'm attempting the build the plugin, but am getting an error. Not sure if it's related to my build environment or if the dependencies have changed?

```
C:\GIT_Workspaces\terraform-provider-bigip>make bin
github.com/aws/aws-sdk-go (download)
package github.com/aws/aws-sdk-go/private/endpoints: cannot find package "github.com/aws/aws-sdk-go/private/endpoints" in any of:
        C:\Go\src\github.com\aws\aws-sdk-go\private\endpoints (from $GOROOT)
        C:\Users\MYUSER\go\src\github.com\aws\aws-sdk-go\private\endpoints (from $GOPATH)
make: *** [get-deps] Error 1
```

It doesn't appear like one of the origin paths exists anymore as of Terraform v0.8.1?

```
{
	"checksumSHA1": "Esab5F8KswqkTdB4TtjSvZgs56k=",
	"origin": "github.com/hashicorp/terraform/vendor/github.com/aws/aws-sdk-go/private/endpoints",
	"path": "github.com/aws/aws-sdk-go/private/endpoints",
	"revision": "594014d4f65f61c1399fc337e5fc2211b5a28474",
	"revisionTime": "2016-11-22T16:59:48Z"
}
```
v0.8.1
https://github.com/hashicorp/terraform/tree/v0.8.1/vendor/github.com/aws/aws-sdk-go/private

v0.8.2
https://github.com/hashicorp/terraform/tree/v0.8.2/vendor/github.com/aws/aws-sdk-go/private

**Comment by jakauppila** [comment]
After looking at this a bit more, it's on me with my lack of familiarity with building Go projects. I had the repo cloned to a path outside of my GOPATH, so after working within that structure, I'm getting a bit further.

1. Current master of https://github.com/DealerDotCom/terraform-provider-bigip cloned to:
C:\Users\Jared\go\src\github.com\DealerDotCom\terraform-provider-bigip

2. Execute 'make get-deps && make bin && make dist'

3. Receive this error: https://gist.github.com/Jakauppila/e0d57b2aa488079d5c12f875ce1db44c

It appears that the build is attempting to use the up-to-date version of `github.com\scottdware\go-bigip` that I have pulled to my GOPATH rather than the specific revision that is vendored in the repository.

In fact, I just verified this, by doing a `git checkout c794a5a0d4c0b85783600459852c93c1000a7702' within `C:\Users\Jared\go\src\github.com\scottdware\go-bigip` and the provider builds correctly. This shouldn't be required as it should be using the vendored version, right?

**Comment by jakauppila** [comment]
I think this is a result of how the makefile was defined; without moving into a different project, it should use the vendored projects correctly.

**Comment by mattcanty** [comment]
Hi @jakauppila you seem to be the only person looking after this repo. I'm having a great deal of difficulty getting it to build and I am currently on this same issue. Have you got any tips?

**Comment by jakauppila** [comment]
@mattcanty What's the output when you try to do a `make bin` off of master?

**Comment by mattcanty** [comment]
I followed the commands by [pcfens](https://github.com/DealerDotCom/terraform-provider-bigip/issues/37) and upgraded to the latest version of Terraform and it actually built to my surprise!

But then I still have an error which I've added to [this ticket](https://github.com/DealerDotCom/terraform-provider-bigip/issues/54)
