### ISSUE TITLE
Import latest version of the go-bigip library into project

### ISSUE THREAD

**Issue by kkloos1** [DealerDotCom/terraform-provider-bigip#43]
Some recent updates to the go-bigip library added features I'm looking to utilize in my environment (support for setting VS SSL Profiles, VLANs, and SNATPools). 

I attempted to import the latest go-bigip library from https://github.com/scottdware/go-bigip into the terraform-provider-bigip project I setup locally but got these errors when trying to compile the source code:

![image](https://cloud.githubusercontent.com/assets/25256104/24879713/5ac50e00-1dfd-11e7-9c60-63b7a52daab0.png)

Looks like some of the functions in go-bigip were updated since it was imported last ( ~10 months ago) and the calls in the provider-bigip code need to be updated to support these changes. Would it be possible to resolve these conflicts and pull the latest version of the go-bigip library into this project?

**Comment by jakauppila** [comment]
I would guess https://github.com/scottdware/go-bigip/pull/20 caused this incompatibility.
