### ISSUE TITLE
consider moving to terra-farm or core?

### ISSUE THREAD

**Issue by josephholsten** [DealerDotCom/terraform-provider-bigip#48]
I don't know if bigip is ready to start joining core, but if it is I'd like to help with the process.

If we want to not actually be in core, some folks are putting together an org like [sous-chefs](https://github.com/sous-chefs) does for chef cookbooks. Then maintainers can help each other out reviewing, merging and releasing changes. The main advantage is having more than one maintainer who can pass the torch. If that sounds interesting, the conversation is happening at https://github.com/terra-farm/meta/issues

If that doesn't sound ideal, please let me know!

**Comment by jakauppila** [comment]
I'd definitely be interested in seeing this happen.

**Comment by aburnett** [comment]
Looks like https://github.com/terraform-providers is the new place to be.

https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/

**Comment by josephholsten** [comment]
One of the requirements is to have at least one active participant to be maintainer. Who makes the most sense for that role?

**Comment by josephholsten** [comment]
Oh, and acceptance tests. Anyone got thoughts on how we could test this against a live API?

**Comment by aburnett** [comment]
I petitioned for someone to provide a bigip on a cloud provider like aws a while back. There were no takers but this would, in my mind, be a pre-req for any sort of public adoption.

**Comment by josephholsten** [comment]
It's also a prerequisite for being in core.

**Comment by aburnett** [comment]
Right, that was the blocker for #20.

**Comment by gliptak** [comment]
Would test running defined (captured from real interactions) input/outputs be fulfilling the acceptance test requirement?

This is how ```cloudflare-go``` testbed works https://github.com/cloudflare/cloudflare-go/blob/master/ssl_test.go

**Comment by pdxfixit** [comment]
https://github.com/f5devcentral/terraform-provider-bigip exists now, and seems to have the right attention (https://github.com/f5devcentral/terraform-provider-bigip/issues/1).  Closing.
