### ISSUE TITLE
Much needed TLC!

### ISSUE THREAD

**Issue by mattcanty** [DealerDotCom/terraform-provider-bigip#53]
I've got a lot of value from this provider, but it's current state is pushing me away _fast_.

I can see from various merged PRs that there is a fix to an issue with node predicates that has been fixed. I'd like to start using this.

## Problem 1
Releases are not being made, and you are not publishing the dist directory. There is no way for me to simply download and start using the builds straight away.

## Problem 2
The readme does not match reality. `make get-deps` does not work, because that task is not defined!

## Problem 3
Dependencies are out of date. The project partially builds but ultimately fails due to `waiter` and `endpoints` missing from `aws-sdk-go/private`.

**Comment by mattcanty** [comment]
Closed because it does not help.

**Comment by devinsba** [comment]
You created this issue less than 2 hours ago. The people who have written code for this are around sporadically, if you need fixes you can feel free to create pull requests with them

**Comment by mattcanty** [comment]
Closed because I felt it was more of a whinge than being constructive.

I currently have very little Go experience, not even done a hello world yet. I'd appreciate the simple inclusion of the dist directory or an update to the releases so that I can see if any of the most recent changes fix my real current issue: #54

**Comment by pdxfixit** [comment]
FWIW, I totally sympathize with your points, @mattcanty.

For my part, our team has moved in a different direction, and that's shifted what time I had available to work on this.

That said, I'll still do what I can, when+where I can.
