### ISSUE TITLE
Standardize partition / name convention

### ISSUE THREAD

**Issue by aburnett** [DealerDotCom/terraform-provider-bigip#6]
@kzittritsch @RobWC @ivey Currently the plugin is a little wishy washing in how it handles specifying the Partition for the various resources. Most resources have partition + name as properties but name can contain the partition in most cases.

I propose getting rid of `Partition` as a property and just having `Name` enforced as  _"/Partition/Name"_. This would greatly simplify dealing with the F5 API and make the resource definitions in the terraform files more explicit.

This would be a breaking change, so wanted to get some buy in first. Thoughts?

Example

```
resource "bigip_ltm_policy" "policy" {
   name = "my-policy"
   partition = "Common"
```

would become

```
resource "bigip_ltm_policy" "policy" {
   name = "/Common/my-policy"
```

Names not matching `/[\w-_.]+/[\w-_.]+` will throw a validation error.

**Comment by kzittritsch** [comment]
:+1: this change sounds good to me

**Comment by RobWC** [comment]
No issues with us! I was running into this issue and it would be a welcome change. 👍

**Comment by aburnett** [comment]
K, this is in progress

**Comment by aburnett** [comment]
Mainline now requires fully named resources.
