### ISSUE TITLE
Supported versions ? Bad gateway response

### ISSUE THREAD

**Issue by VAdamec** [DealerDotCom/terraform-provider-bigip#8]
Hi, 
 which versions are supported ? I'm getting this strange error on version 11.6.0, via Ansible v2 f5 module it's possible to setup nodes/pools without any issue (so account and access is ok).

Bad Gateway!

The proxy server could not handle the request <em><a href="/mgmt/tm/net/xxxx">GET&nbsp;/mgmt/tm/net/self</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p>

**Comment by aburnett** [comment]
I've been using it against 11.5.

Which auth mechanism are you using (user/pass or token). Can you curl that url?

```
curl -u "username:password" "https://ltm-host/mgmt/tm/net/self"
```

**Comment by VAdamec** [comment]
Using user/pass and there is no response, just connect and wait

curl -u "terradata-demo:xxxxx" 'https://xx.xx.xx.xx/mgmt/tm/net/self' -kv
-   Trying xx.xx.xx.xx...
- Connected to xx.xx.xx.xx (xx.xx.xx.xx) port 443 (#0)
- TLS 1.2 connection using TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
- Server auth using Basic with user 'terradata- demo’
  > GET /mgmt/tm/net/self HTTP/1.1
  > Host: 10.24.50.180
  > Authorization: Basic xxxxxx
  > User-Agent: curl/7.43.0
  > Accept: _/_
  >
  …

Simple request to 'https://xx.xx.xx.xx’ is ok. It’s virtual server on Viprion, it should behave same as standalone LTM, but probably not.

**Comment by aburnett** [comment]
Ya, so there's something else going on here outside of the provider it sounds like then. I assume that's the same host/user/password you're using via ansible?

**Comment by VAdamec** [comment]
Yes, same setup as for ansible (running from same host)

**Comment by kzittritsch** [comment]
Just want to throw in my two cents: restarting the REST service on the LTM has resolved any "Bad Gateway" responses for us.  `restart /sys service restjavad`

Edit: also worth noting that the ansible modules communicate via SOAP (bigsuds)

**Comment by VAdamec** [comment]
Restart helps :-)

**Comment by aburnett** [comment]
Yes. Ansible uses the rest api. The provider uses rest.
